# Generated by Django 3.2.4 on 2021-08-20 08:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projectapp', '0001_initial'),
        ('subscribeapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subsciption',
            new_name='Subscription',
        ),
    ]
